<?php
/**
 * Created by PhpStorm.
 * User: liser
 * Date: 08.02.2019
 * Time: 1:12
 */

// Задание 1-4
include "Product.php";

class SaleProduct extends Product {
    private $dateOfSale;
    private $quantity;

    function __construct($id, $name, $price, $category, $vendor, $dateOfSale, $quantity) {
        parent::__construct($id, $name, $price, $category, $vendor);
        $this->dateOfSale = $dateOfSale;
        $this->quantity = $quantity;
    }

    public function showProductInfo() {
        parent::showProductInfo(); // TODO: Change the autogenerated stub
        echo "Количество: $this->quantity; Дата продажи: $this->dateOfSale <br>";
    }
}